### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by aim12340** [termsfeed/termsfeed-cookie-consent-4-1-gtm-community-template#2]
Hi.  Is there any info on how to set this up in tag manager?

It shows the dialog and sets the cookies correctly, and fires off a updateConsentState(consentSettings) when the dialog is dismissed.

But it doesn't fire updateConsentState(consentSettings) ever again.  It doesn't fire when I navigate to a new page, and it doesn't set the defaults (all disabled) at all.

I've tried firing it from "all pages" and "consent initializatin - all pages" triggers and it behaves the same.

Am I doing something wrong?

**Comment by aim12340** [comment]
Thanks for the update.  Here's what happens when I use it...  To be clear, I'm not tagging any of my own scripts, just loading gtag for analytics.

I'm using the Tag Assistant to track a page loading.  I've already accepted cookies, so they are all accepted when this page loads.

I see these events in the order:

Consent Initilaization - not tags loaded,  consent tab is empty

Initialization - TermsFeed Cookie Consent 4.1 tag runs here, consent is still empty

Consent - not tags loaded.  Consent shows all defaults set to denied.  This event and all the folowing have a warning message "A tag read consent state before a default was set"

Container Loaded - Google Tag tag runs.  Consent shows Defaults are denied and Current State is all denied.

Dom Ready - no changes

Window Loaded - no changes

Consent (3 times) - no tags run.  Consent becomes Defaults all denied and On-page update all granted.

So it looks like there are 2 problems.

1) The "A tag read consent state before a default was set" message might not be a serious problem.  This message isn't there is i use the Consent Initialization trigger, but google say your shouldn't use that for consent, just setting the defaults I think.  It seems you might need 2 tags - an init defaults tag on a Consent Initialization trigger and your current tag on an Initialization trigger.

2) At the time the Google Tag runs, all the consents are denied.  The users consent choices aren't applied until after the Dom Ready and Winows Loaded events.

I'm new to tag manager templates and concent v2, so it's possible I've misunderstood. something.

Thanks.

**Comment by aim12340** [comment]
If it helps, here's a TPL I just made that just sets the defaults.  I run it from the Consent Initialization All Pages trigger and it seems to work fine, and removes the "A tag read consent state before a default was set" message when your tag is used on the Initialization trigger.

```
___INFO___

{
  "type": "TAG",
  "id": "cvt_temp_public_id",
  "version": 1,
  "securityGroups": [],
  "displayName": "Consent Defaults",
  "brand": {
    "id": "brand_dummy",
    "displayName": ""
  },
  "description": "Consent Defaults - All Denied",
  "containerContexts": [
    "WEB"
  ]
}


___TEMPLATE_PARAMETERS___

[]


___SANDBOXED_JS_FOR_WEB_TEMPLATE___

// Enter your template code here.
const setDefaultConsentState = require('setDefaultConsentState');

setDefaultConsentState({
  ad_storage: 'denied',
  ad_user_data: 'denied',
  ad_personalization: 'denied',
  analytics_storage: 'denied'
});

// Call data.gtmOnSuccess when the tag is finished.
data.gtmOnSuccess();


___WEB_PERMISSIONS___

[
  {
    "instance": {
      "key": {
        "publicId": "access_consent",
        "versionId": "1"
      },
      "param": [
        {
          "key": "consentTypes",
          "value": {
            "type": 2,
            "listItem": [
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "consentType"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "ad_storage"
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  }
                ]
              },
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "consentType"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "ad_user_data"
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  }
                ]
              },
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "consentType"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "ad_personalization"
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  }
                ]
              },
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "consentType"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "analytics_storage"
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  }
                ]
              }
            ]
          }
        }
      ]
    },
    "clientAnnotations": {
      "isEditedByUser": true
    },
    "isRequired": true
  }
]


___TESTS___

scenarios: []


___NOTES___

Created on 23/04/2024, 18:17:12


```

**Comment by aim12340** [comment]
I'm using this code to set the consent from your cookie when the tag is loaded.  This makes it set the consent on the tag manager initialization event.  I've added a few comments to the code (in bold)...

const log = require('logToConsole');
const getCookieValues = require('getCookieValues');
const setDefaultConsentState = require('setDefaultConsentState');
const updateConsentState = require('updateConsentState');
const decodeUriComponent = require('decodeUriComponent');
const JSON = require('JSON');
const Object = require('Object');
const injectScript = require('injectScript');
const queryPermission = require('queryPermission');
const callInWindow = require('callInWindow');
const setInWindow = require('setInWindow');

**// I removed this as the default consent should be set in the Consent Initialization event**
/\*setDefaultConsentState({
  ad_storage: 'denied',
  ad_user_data: 'denied',
  ad_personalization: 'denied',
  analytics_storage: 'denied'
});\*/

let consentSettings = {
    ad_storage: 'denied',
    ad_user_data: 'denied',
    ad_personalization: 'denied',
    analytics_storage: 'denied'
};

setInWindow('callback_scripts_all_loaded', function () {
    log('callback_scripts_all_loaded');
    consentSettings = {
        ad_storage: 'granted',
        ad_user_data: 'granted',
        ad_personalization: 'granted',
        analytics_storage: 'granted',
    };
    updateConsentState(consentSettings);
});

setInWindow('callback_scripts_specific_loaded', function (level) {
    log('callback_scripts_specific_loaded', level);
    switch (level) {
        case 'tracking':
            consentSettings.analytics_storage = 'granted';
            break;
        case 'analytics_storage':
            consentSettings.ad_storage = 'granted';
            consentSettings.ad_user_data = 'granted';
            consentSettings.ad_personalization = 'granted';
            break;
    }
    updateConsentState(consentSettings);
});

function initCookieConsent() {
    callInWindow('cookieconsent.run', {
        "notice_banner_type": data.notice_banner_type,
        "consent_type": "express",
        "palette": data.palette,
        "language": data.language,
        "page_load_consent_levels": ["strictly-necessary"],
        "notice_banner_reject_button_hide": false,
        "preferences_center_close_button_hide": false,
        "page_refresh_confirmation_buttons": false,
        "callbacks": {
            "scripts_all_loaded": "callback_scripts_all_loaded",
            "scripts_specific_loaded": "callback_scripts_specific_loaded"
        },
        "callbacks_force": true
    });
}


**// This function reads the cookie and sets the cookie consent,  It is called immediately, before your script is loaded asynchronously.  This sets the consent during the Tag Manager Initialization event**
function initConsentFromCookie(){
    let cookie = getCookieValues("cookie_consent_level")[0];
    if (cookie == undefined)
        return;
    const object = JSON.parse(cookie);
    consentSettings.analytics_storage = object.tracking ? "granted" : "denied";
    consentSettings.ad_storage = object.targeting ? "granted" : "denied";
    consentSettings.ad_user_data = consentSettings.ad_storage;
    consentSettings.ad_personalization = consentSettings.ad_storage;
    updateConsentState(consentSettings);
}
//execute function immediatley
initConsentFromCookie();


let url = 'https://www.termsfeed.com/public/cookie-consent/4.1.0/cookie-consent.js';
if (queryPermission('inject_script', url)) {
    injectScript(url, initCookieConsent, data.gtmOnFailure);
   **//  Added data.gtmOnSuccess as it seems to be required when the tag completes sucessfully.**
    data.gtmOnSuccess();
} else {
    data.gtmOnFailure();
}


I think this solves my problem.  Calling initConsentFromCookie sets the consent early in the page load (during the Initialization event), so it is in place when later tags are executed, in my case the gtag tag.

It would be great if you can merge this in - I don't want to use a custom tag as it won't get updates.

**Comment by aim12340** [comment]
I don't see your latest version in tag manager yet, but I like the changes.

I do think you have a logic problem though.  As I understand it google want a default set and then actual values set.  at the moment your logic is:

```
if can inject script then
    if cookie exists 
        then
            set consent values
            initCookieConsent()
        else
            set consent defaults
```
would be better as

```
set consent defaults
if cookie exists then
    set consent values
if can inject script then
    initCookieConsent()
```
this makes sure the defaults are always set (which i think google will pefer) and the cookies always set consent values.

so i would change
```
    if (!cookie) {
        denyAllLevels();
        return;
    }
```
to
```
    if (!cookie) {
        return;
    }
```
and
```
if (queryPermission('inject_script', url)) {
    initConsentFromCookie();
    injectScript(url, initCookieConsent, data.gtmOnFailure);
    data.gtmOnSuccess();
} else {
    data.gtmOnFailure();
}
```
to
```
denyAllLevels(); // i would rename this as it's setting defaults not final consent
initConsentFromCookie();
if (queryPermission('inject_script', url)) {
    injectScript(url, initCookieConsent, data.gtmOnFailure);
    data.gtmOnSuccess();
} else {
    data.gtmOnFailure();
}
```

In reality, the if (queryPermission('inject_script', url)) will probably never fail so this might not make any practical difference, but the flow will be easier to read. 

I also like that it seperates the initial consent handling from the UI code.

My other problem: "A tag read consent state before a default was set" I think is more my problem, so ignore that for now.  I'm loading another google script asynchronously outside tag manager and I think that's loading first somtimes and google is saying that that script has read consent state.  I need to look into it more but i'll start anoher issue if needed.

Thanks.

**Comment by aim12340** [comment]
FYI I tried to import your latest tpl but it wouldn't import.

**Comment by termsfeed** [comment]
This should work now. We've pushed a new version ~2 weeks ago.

If there are any other errors, please open a new ticket so we can troubleshoot.
