### ISSUE TITLE
Include wait_for_update on the setDefaultConsent Call

### ISSUE THREAD

**Issue by philpott** [termsfeed/termsfeed-cookie-consent-4-1-gtm-community-template#3]
https://github.com/termsfeed/termsfeed-cookie-consent-4-1-gtm-community-template/blob/4e4c9c912256194f473a8ad854f6f70ca2e576f5/template.tpl#L156

When reviewing your template we've noticed that the `setDefaultConsentState` call does not include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. This is required for any asynchronous consent management script load to delay tag execution.

**Comment by termsfeed** [comment]
@philpott Thanks! We've pushed a new version that includes the `wait_for_update` for `setDefaultConsentState`.
