### ISSUE TITLE
Fields for notice_banner_reject_button_hide + preferences_center_close_button_hide

### ISSUE THREAD

**Issue by aim12340** [termsfeed/termsfeed-cookie-consent-4-1-gtm-community-template#4]
Hi,

Can you add fields for more configuartion to the UI?

For me it would be very useful to have UI options for notice_banner_reject_button_hide and preferences_center_close_button_hide.

Thanks.

**Comment by termsfeed** [comment]
@aim12340 We've added a few options now.

**Comment by aim12340** [comment]
Thanks!
